/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MarkdownPreview: typeof import('./src/components/MarkdownPreview/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NLayout: typeof import('naive-ui')['NLayout']
    NSpin: typeof import('naive-ui')['NSpin']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
  }
}

// For TSX support
declare global {
  const MarkdownPreview: typeof import('./src/components/MarkdownPreview/index.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NSpin: typeof import('naive-ui')['NSpin']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
}